-- ================================================================
-- Migracion 003: Poblar socios_profesores con centro (Excel 31-mar-2026)
-- Ejecutar en Supabase > SQL Editor > New query > Run
-- ================================================================

INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 2 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 3 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 7 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 10 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 14 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 16 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 17 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 19 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 20 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 25 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 26 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 32 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 35 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Quimica y Fisica' FROM socios WHERE num_socio = 37 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Dept.Ingenieria Electronica' FROM socios WHERE num_socio = 38 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 40 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 42 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 43 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 46 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 47 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 51 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 52 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 53 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Filosofia y Letras' FROM socios WHERE num_socio = 54 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 55 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Educacion' FROM socios WHERE num_socio = 56 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Medicina' FROM socios WHERE num_socio = 57 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. F.y letras Ciencias Comunicación' FROM socios WHERE num_socio = 58 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 60 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac,Ciencias Economicas' FROM socios WHERE num_socio = 61 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Ingenieco Telecomunicacion' FROM socios WHERE num_socio = 62 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'P.T.E.V Enfermeria' FROM socios WHERE num_socio = 63 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 64 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 65 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 66 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Derecho' FROM socios WHERE num_socio = 67 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. C.Economicas y Empresariales' FROM socios WHERE num_socio = 68 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 69 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 70 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Filosofia y Letras' FROM socios WHERE num_socio = 71 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 72 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Filosofia y Letras' FROM socios WHERE num_socio = 74 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Escuela Ingenieria Industrial' FROM socios WHERE num_socio = 75 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 76 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias de la Educacion' FROM socios WHERE num_socio = 77 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Ciencias Economicas' FROM socios WHERE num_socio = 78 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 79 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Filosofia y Letras' FROM socios WHERE num_socio = 80 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias de la Salud' FROM socios WHERE num_socio = 81 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Ciencias Biologia' FROM socios WHERE num_socio = 83 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 84 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Medicina' FROM socios WHERE num_socio = 85 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac.Ciencias Economicas' FROM socios WHERE num_socio = 86 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencieas' FROM socios WHERE num_socio = 87 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias' FROM socios WHERE num_socio = 88 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'EISI Informatica' FROM socios WHERE num_socio = 89 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Derecho' FROM socios WHERE num_socio = 90 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Estudios Sociales y Trabajo' FROM socios WHERE num_socio = 91 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 92 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 93 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias de la Salud' FROM socios WHERE num_socio = 94 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Fisioterapia' FROM socios WHERE num_socio = 95 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Economicas' FROM socios WHERE num_socio = 96 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 97 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 98 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Cieincas Sociales y Trabajo' FROM socios WHERE num_socio = 99 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 101 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Educacion' FROM socios WHERE num_socio = 102 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencas Economicas' FROM socios WHERE num_socio = 103 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias de la Salud' FROM socios WHERE num_socio = 104 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Escuela Ingenieria Industrial' FROM socios WHERE num_socio = 105 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias' FROM socios WHERE num_socio = 106 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias' FROM socios WHERE num_socio = 107 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Filosofia y Ltras' FROM socios WHERE num_socio = 108 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Escuela Tecnica Sup. Ing.Informatica' FROM socios WHERE num_socio = 109 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Educacion' FROM socios WHERE num_socio = 110 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Medicina' FROM socios WHERE num_socio = 111 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 112 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Psicologia' FROM socios WHERE num_socio = 113 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, NULL FROM socios WHERE num_socio = 114 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias de la Salud (Fisioterapia)' FROM socios WHERE num_socio = 115 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Psicología' FROM socios WHERE num_socio = 116 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'E.T.S Ingenieros Industriales' FROM socios WHERE num_socio = 117 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Filisofía y Letras (Historia)' FROM socios WHERE num_socio = 118 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias Educación (Didáctica esc)' FROM socios WHERE num_socio = 119 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSI Ingenierias' FROM socios WHERE num_socio = 120 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias Educación (Didáctica esc)' FROM socios WHERE num_socio = 121 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Filosofía y Letras (Filología Hispánica)' FROM socios WHERE num_socio = 122 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Esc.Tec.Sup. Arquitectura' FROM socios WHERE num_socio = 123 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSII Informática' FROM socios WHERE num_socio = 124 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias Educación' FROM socios WHERE num_socio = 125 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias, Biología' FROM socios WHERE num_socio = 126 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Medicina' FROM socios WHERE num_socio = 127 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias, Biologia' FROM socios WHERE num_socio = 128 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Ciencias , Quimicas' FROM socios WHERE num_socio = 129 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Filosofía y Letras (Depto de Traducción e Interpretación)' FROM socios WHERE num_socio = 130 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Facultad de Medicina' FROM socios WHERE num_socio = 131 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac. Ciencias Educacion' FROM socios WHERE num_socio = 132 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Filos y Letras, Literatura Española' FROM socios WHERE num_socio = 133 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSII Telecomunicacion' FROM socios WHERE num_socio = 134 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Derecho' FROM socios WHERE num_socio = 135 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSII Telecomunicacion' FROM socios WHERE num_socio = 136 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Derecho' FROM socios WHERE num_socio = 137 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSII Telecomunicacion' FROM socios WHERE num_socio = 138 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Psicología' FROM socios WHERE num_socio = 139 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Psicologia' FROM socios WHERE num_socio = 140 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Filosofia y Letras  Geo/Historia' FROM socios WHERE num_socio = 141 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Medicina' FROM socios WHERE num_socio = 142 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'ETSII Telecomunicacion' FROM socios WHERE num_socio = 143 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Fac Psicología' FROM socios WHERE num_socio = 144 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'Filos y Letras, Filolog Inglesa' FROM socios WHERE num_socio = 145 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;
INSERT INTO socios_profesores (socio_id, centro) SELECT id, 'F. Ciencias y ETS Ingenieros Industriales' FROM socios WHERE num_socio = 146 AND tipo = 'profesor' ON CONFLICT (socio_id) DO UPDATE SET centro = EXCLUDED.centro;

-- Total: 112 registros (85 con centro, 27 sin centro)
-- Verificar:
SELECT COUNT(*) AS total FROM socios_profesores;
SELECT COUNT(*) AS con_centro FROM socios_profesores WHERE centro IS NOT NULL;
SELECT s.num_socio, s.apellidos, sp.centro FROM socios s JOIN socios_profesores sp ON s.id = sp.socio_id ORDER BY s.num_socio LIMIT 20;